server.port: 8090


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://51.250.103.114:5432/hrBackDb"
#    url: "jdbc:postgresql://localhost:5432/hrBackDb"
    username: postgres
    password: postgres

  main:
    allow-bean-definition-overriding: true
#    hibernate:
    allow-circular-references: true
server.error.include-exception: true
server.error.include-stacktrace: always